erreduarte
*** Found local files:
***   * /home/erreduarte/airflow/logs/dag_id=open_weather_DAG/run_id=scheduled__2024-10-06T08:00:00+00:00/task_id=Load_Staging_Table/attempt=1.log
[2024-10-06T10:02:17.221+0100] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-06T10:02:17.270+0100] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: open_weather_DAG.Load_Staging_Table scheduled__2024-10-06T08:00:00+00:00 [queued]>
[2024-10-06T10:02:17.288+0100] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: open_weather_DAG.Load_Staging_Table scheduled__2024-10-06T08:00:00+00:00 [queued]>
[2024-10-06T10:02:17.288+0100] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-06T10:02:17.315+0100] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): Load_Staging_Table> on 2024-10-06 08:00:00+00:00
[2024-10-06T10:02:17.323+0100] {standard_task_runner.py:72} INFO - Started process 2550333 to run task
[2024-10-06T10:02:17.329+0100] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'open_weather_DAG', 'Load_Staging_Table', 'scheduled__2024-10-06T08:00:00+00:00', '--job-id', '756', '--raw', '--subdir', 'DAGS_FOLDER/DAG_OPEN_WEATHER.py', '--cfg-path', '/tmp/tmpzzfpng6i']
[2024-10-06T10:02:17.333+0100] {standard_task_runner.py:105} INFO - Job 756: Subtask Load_Staging_Table
[2024-10-06T10:02:17.512+0100] {task_command.py:467} INFO - Running <TaskInstance: open_weather_DAG.Load_Staging_Table scheduled__2024-10-06T08:00:00+00:00 [running]> on host erreduarte
[2024-10-06T10:02:17.784+0100] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='renanduarte' AIRFLOW_CTX_DAG_ID='open_weather_DAG' AIRFLOW_CTX_TASK_ID='Load_Staging_Table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-06T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-06T08:00:00+00:00'
[2024-10-06T10:02:17.785+0100] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-06T10:02:17.845+0100] {base.py:84} INFO - Retrieving connection 'microsoft_azure_database'
[2024-10-06T10:02:18.315+0100] {sql.py:531} INFO - Running statement: 
                BULK INSERT 
                    dbo.OpenWeatherData_staging
                FROM 
                    'Weather_Data__Silver.csv'
                WITH (
                    DATA_SOURCE     = 'OpenWeatherData',
                    ROWTERMINATOR   = '0x0a',
                    FIELDTERMINATOR = ',',
                    FIRSTROW        = 2,
                    CODEPAGE = '65001'
                        );
                        
                , parameters: None
[2024-10-06T10:02:18.465+0100] {sql.py:540} INFO - Rows affected: 51
[2024-10-06T10:02:18.559+0100] {python.py:240} INFO - Done. Returned value was: Table sucessfully populated
[2024-10-06T10:02:18.683+0100] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-06T10:02:18.683+0100] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=open_weather_DAG, task_id=Load_Staging_Table, run_id=scheduled__2024-10-06T08:00:00+00:00, execution_date=20241006T080000, start_date=20241006T090217, end_date=20241006T090218
[2024-10-06T10:02:18.743+0100] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-06T10:02:18.812+0100] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-06T10:02:18.823+0100] {local_task_job_runner.py:245} INFO - ::endgroup::
